### ISSUE TITLE
Inconsistent Regex matching

### ISSUE THREAD

**Issue by jangrewe** [userfrosting/fortress#22]
If i use this regex 
```
^# word1( word2)*\n# Example (.|\n)*$
```
the following input:
```
# word1 word2
# Example / more words here
foobar
```
Is valid in the client-side validation, but on the server-side it is considered invalid. =(

Here's an example that says the regex works in JS and PCRE: https://regex101.com/r/3zbadT/2

(moved from https://github.com/userfrosting/UserFrosting/issues/857)

**Comment by jangrewe** [comment]
In my `schema` i have this:
```
lines:
  validators:
    required:
      label: Lines
      message: "Please add your diff."
    length:
      label: Lines
      min: 100
      message: "Please include all diff lines."
    regex:
      regex: ^# diff( all)*(\r)*\n# Betaflight (.|\r*\n)*$
      message: "Your diff must start with '# diff [all]'."
  transformations:
  - trim
  - purge
```
and some example input would be:
```
# diff all
# Betaflight / BETAFLIGHTF3 (BFF3) 3.3.0 Mar  2 2018 / 03:38:14 (177472b4f) MSP API: 1.37
defaults nosave
name BetaWhoop

```
